### ISSUE TITLE
Hide module loading operations properly(?)

### ISSUE THREAD

**Issue by micalevisk** [clinicjs/node-clinic-flame#144]
Let's say I have the following files:

<details>
<summary><code>foo.js</code></summary>

```js
'use strict'
function initPayload (idSize = 20) {
  if (idSize < 6) throw Error('idSize must be greater than 5')
  return function payload () {
    let chars = ''
    let n = idSize
    const date = Date.now()
    const radix = 36
    n *= n * idSize
    while (n--) {
      const num = date + n
      chars += num.toString(radix).toUpperCase()
    }
    const id = chars.slice(-idSize)
    return { date, id }
  }
}
module.exports = initPayload
```

</details>

<details>
<summary><code>main.js</code></summary>

```js
'use strict'
const express = require('express')
const initPayload = require('./foo')
const app = express()
const payload = initPayload()
app.get('/', (req, res) => {
  res.send(payload())
})
app.listen(3000)
```

</details>

Then with Clinic Flame `9.1.0`, doing `clinic flame -- node main.js` I got this graph:

![image](https://user-images.githubusercontent.com/13461315/141528872-289221eb-f2c0-4b1c-86f3-cc3ee744ea78.png)

in which the three hottest frames are in "`line: 1 column: 1`". Aren't they "module loading" operations? If so, they should be hidden, right?

**Comment by RafaelGSS** [comment]
yeah, looks like a bug.

Which nodejs version are you using and which OS?

**Comment by micalevisk** [comment]
node: 16.3.0
OS: Linux (Ubuntu)

**Comment by BridgeAR** [comment]
AFAIK this is working as expected. The loading part is about Node.js stack frames that should show up when clicking on the button. I guess the confusion is about the description.

**Comment by micalevisk** [comment]
I just tested this with nodejs v14.17.3 and got another flame graph (ignoring WebAssemblt & Node JS & V8)

![image](https://user-images.githubusercontent.com/13461315/141583779-83a86456-b24e-476c-80eb-b84cecc1a0b4.png)

Here's the code with both clinic's output: https://gitlab.com/micalevisk/node-clinic-flame-issue-144

but yeah, those entry files (`line:1 column:1`) are still the hottest frames. I tested with clinic 8 as well.

---

What do you guys think about adding a checkbox to let use hide those files? I don't think they are useful in some cases

**Comment by RafaelGSS** [comment]
I didn't understand what do you mean in the first iteration time, sorry. Now it's clear, thanks @BridgeAR.

---

> What do you guys think about adding a checkbox to let use hide those files? I don't think they are useful in some cases

I feel that this information is pretty useful to identify the call stack.

**Comment by micalevisk** [comment]
> I feel that this information is pretty useful to identify the call stack.

sure. What about _ignoring_ them so they don't show up as a 'hottest frames'?

**Comment by RafaelGSS** [comment]
Yes, it could be good. Would you like to make a PR? Remember to add unit tests.

**Comment by micalevisk** [comment]
I have no clue on where to start nor enough time do to explore for now. I'll try later (in few weeks) if no one takes this.
