### ISSUE TITLE
Flamechart with high T _host_get_clock_service

### ISSUE THREAD

**Issue by sky-nunomarcos** [clinicjs/node-clinic-flame#160]
Hi There, Thanks for your fantastic solution :) 

I'm currently performing some debug to my nodejs implementation using clinic flame and trying to understand if this huge T _host_get_clock_service block is something related with my code itself or if this is result of clinic work?
![image](https://user-images.githubusercontent.com/23661699/153642439-ea602f6e-e59f-43f0-8419-a74bb3a06197.png)

Thanks for your support.

**Comment by RafaelGSS** [comment]
This is a SYSCALL to the OS to get the current time. It's related to your code/dependencies. Prometheus maybe?

**Comment by sky-nunomarcos** [comment]
Ho, thanks @RafaelGSS :) 
Do you have idea if there is some way to get some more detail on this block? like launching node with debug level?

**Comment by sky-nunomarcos** [comment]
No, it is a NodeJs implementation using express

**Comment by RafaelGSS** [comment]
I'd recommend you check the code dependencies. Try to follow this tutorial: https://nodejs.org/en/docs/guides/simple-profiling/. It might bring some light to your finding.

**Comment by sky-nunomarcos** [comment]
Thanks @RafaelGSS will do 👍 Regards
